### ISSUE TITLE
permission to use part of your UI

### ISSUE THREAD

**Issue by ibnz36** [Vap0r1ze/nasin-sona#2]
Today, before knowing this was a thing, I started my own chrome extension that does exactly the same thing (not finished but can be found at https://github.com/Brian3647/ni-li-seme) and now I'm not sure what to do.
I considered just contributing to this but:
1. I'm not a fan of userscripts
2. The way one writes typescript is very different from one person to another and this specific one feels weird to me
3. I'd want some experience working with chrome extensions

And I considered taking part of your UI (because it's similar to nimi.li and it's simple enough) but it seems the project does not have a license. Could I use part of your code? I don't plan on making any money with it, and I also don't mind giving full credit. If needed, DM me on discord (vicmdv)

**Comment by Vap0r1ze** [comment]
yea this is the only userscript ive wrote so its kinda funky, i just added an MIT license and ur free to use whatev
